INSERT INTO USER(ID, USER_NAME, PASSWORD, ROLE) VALUES(10, 'apa', 'apa', 'ADMIN');
INSERT INTO USER(ID, USER_NAME, PASSWORD, ROLE) VALUES(11, 'kate', 'kate', 'USER');
INSERT INTO USER(ID, USER_NAME, PASSWORD, ROLE) VALUES(12, 'anya', 'anya', 'ADMIN');
INSERT INTO USER(ID, USER_NAME, PASSWORD, ROLE) VALUES(13, 'john', 'john', 'USER');
INSERT INTO USER(ID, USER_NAME, PASSWORD, ROLE) VALUES(14, 'mark', 'mark', 'USER');
INSERT INTO USER(ID, USER_NAME, PASSWORD, ROLE) VALUES(15, 'marry', 'marry', 'USER');